# Generated by Django 5.2.1 on 2026-06-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/customUser/'),
        ),
    ]
