# Generated by Django 5.2.6 on 2026-03-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_paid_amount_alter_order_invoice_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='client',
        ),
    ]
