# Generated by Django 5.2.6 on 2025-11-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateField(auto_now=True)),
                ('pub_time', models.TimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
